= Neo4j Slide Types
ifndef::env-github[:icons: font]
ifdef::env-github[:outfilesuffix: .adoc]
:experimental:

This repository documents slide types and presentation techniques and also provides a sample http://markdalgleish.com/projects/bespoke.js[Bespoke.js] presentation that implements several of these ideas.

== Building the presentation

=== Prerequisites

In order to use this project, you only need to be able to run Gradle (specifically, the Gradle Wrappper).
To run Gradle, you need:

. Java Development Kit (JDK) (typically http://openjdk.java.net/install[OpenJDK] or http://www.oracle.com/technetwork/java/javase/downloads/index.html[Oracle JDK]) footnote:[We strongly recommend using http://www.jenv.be[jenv] to manage the JDK.]

Gradle takes care of the rest!

=== Setup

Next, clone the repository and switch to the project directory:

 $ git clone https://github.com/opendevise/neo4j-slide-types.git
   cd neo4j-slide-types

Then, collect the required dependencies and initialize the build:

 $ ./gradlew setup

That's it!
You're all set to build the presentation.

=== Building the static version

You can build a static version of the slides using the following command:

 $ ./gradlew build

The files are built into the _build/bespoke_ directory.
You can view the slides by navigating to _build/bespoke/index.html_ in your browser.

=== Launching the preview server

The preview server makes the presentation available through a local URL.
You can launch the preview server using:

 $ ./gradlew serve

Once the server is running, you can view the slides by navigating to \http://localhost:8000 in your browser.

NOTE: Use kbd:[ctrl+c] to shutdown the preview server.

=== Enabling automatic updates

You can have the build monitor the source files for changes and rerun the tasks whenever a change is detected.
You can also get it to push updates directly to the browser (i.e., LiveReload), saving you from having to manually refresh the page.

In order to activate this arrangement, you'll need two terminal windows open.
In the first window, run the task that generates the slides using continuous build mode:

 $ ./gradlew -t build

This command runs Gradle indefinitely, actively monitoring the source files for changes and rerunning the `build` task whenever a change is detected.
Thanks to Gradle's up-to-date checks, only the tasks affected by the source file(s) that changed will do work.

In the second window, run the task that launches the preview server and activates the LiveReload protocol:

 $ ./gradlew serveLive

Once the server is running, you can view the slides by navigating to \http://localhost:8000 in your browser.
This time, however, you won't have to worry about refreshing the page.

NOTE: Use kbd:[ctrl+c] to shutdown the preview server and LiveReload.

== Catalog

See the <<docs/slide-types#,Neo4j Slide Types>> catalog (in progress) for a list of slide types, their definitions, design concepts and comps and notes about how to apply them.

== Resources

=== Advice for giving presentations

* icon:book[role=black,alt=Book] http://presentationpatterns.com[Presentation Patterns] - Neal Ford, Matthew McCullough, Nathaniel Schutta <- [.green]_Highly recommended!_
  - icon:video-camera[role=black,alt=Video] http://shop.oreilly.com/product/0636920049906.do?code=authd[Companion Video]
* icon:globe[role=blue,alt=Online] icon:book[role=black,alt=Book] http://resonate.duarte.com[Resonate] - Nancy Duarte <- [green]_Also highly recommended!_
* icon:youtube-play[role=red,alt=Video] https://www.youtube.com/watch?v=W_i_DrWic88[Instantly Better Presentations] - Damian Conway <- [blue]_Must see!_
   - icon:file-pdf-o[role=red,alt=PDF] http://damian.conway.org/IBP.pdf[Instantly Better Presentations - Handout]
* https://medium.com/the-rectangle-behind-you/the-rectangle-behind-you-103179fcfc32[The Rectangle Behind You] (Series) - Marcin Wichary
* http://blog.ted.com/10-tips-for-better-slide-decks[10 Tips for Better Slide Decks] - Aaron Weyenberg
* https://www.youtube.com/watch?v=YHierHqxOT0[Training the Team] - Peter Bell
* http://trainingintheopen.com/speaker-training[Training in the Open] - Emma Jane Hogbin Westby
* http://www.bothsidesofthetable.com/2013/10/20/how-to-nail-a-presentation-to-a-crowd[How to Nail a Group Presentation] - Mark Suster
* http://www.inc.com/sims-wyeth/7-ways-to-break-bad-public-speaking-habits.html[7 Ways to Break Bad Speaking Habits] - Sims Wyeth
* https://medium.com/@jakeout/deprecate-keynote-78f0f09424dd[Deprecate Keynote] - Jake Ouellette
* http://headrush.typepad.com/creating_passionate_users/2006/07/a_few_more_pres.html[A Few More Presentation How To's] - Kathy Sierra
* http://frankchimero.com/writing/suggestions-for-speakers[Suggestions for Speakers] - Frank Chimero
* http://www.ted.com/talks/andrew_stanton_the_clues_to_a_great_story[The Clues to a Great Story] - Andrew Stanton
* https://pitchdeck.improvepresentation.com/what-is-a-pitch-deck[What is a pitch deck]

"They were just there to learn about XYZ, and, hopefully, we delivered -- the software was there just to help.
Which is otherwise a great way to think about any slide deck you ever do."
-- Marcin Wichary

"You _really_ don't need your corporate logo on every slide."
-- Damian Conway

=== Other essential background

* http://robbgrindstaff.com/2012/03/narrative-arc-what-the-heck-is-it/[Narrative Arc: What the heck is it?]

=== Terminology

stagedeck:: A presentation that is designed to projected and delivered to an audience (i.e., on stage).
Opposite of an http://presentationpatterns.com/glossary/#infodeck[infodeck].

See the http://presentationpatterns.com/glossary/[Presentation Patterns glossary] for other defined terminology.

=== Reference presentations

The following presentations are either good examples or exhibit bright spots.

* https://speakerdeck.com/pedronauck/reactjs-keep-simple-everything-can-be-a-component[ReactJS: Keep Simple. Everything can be a component] - Pedro Nauck
* http://www.slideshare.net/khalvorson/content-strategy-for-everything[Content Strategy for Everything] - Kristina Halvorson
* https://speakerdeck.com/vanstee/raft-consensus-for-rubyists[Raft: Consensus for Rubyists] - Patrick Van Stee (for its node diagrams)
* https://vimeo.com/108328246[Good Is The Enemy Of Great] (http://www.aresluna.org/the-rectangle-behind-you/good-perfect-talk/#2[slides])
* https://speakerdeck.com/kouphax (nice styling)
* http://www.slideshare.net/jboner
* https://www.youtube.com/watch?v=D85NqSrpzew[How to write well, instantly, every time] - Scott Berkun; has both interesting techniques and just a great talk about producing content

=== Photo archives

* http://unspash.com
* https://pixabay.com
* http://finda.photo
* https://www.flickr.com/photos/usinterior/favorites
* https://www.flickr.com/groups/rnmpco/pool/
* http://mypubliclands.tumblr.com/
* https://www.flickr.com/photos/mypubliclands

=== Design tools and tips

* http://app.programmingfonts.org[Programming Fonts Tester]
* https://coolors.co[Color schemes generator (roulette wheel)]
* https://www.google.com/design/spec/style/color.html#color-color-palette[Material design colors]
* http://thenewcode.com/443/Making-Comic-Book-Speech-Bubbles-with-SVG[Making Comic Book Speech Bubbles with SVG]
