= Neo4j Slide Types
:toc: macro

toc::[]

== Title

A _title slide_ contains the presentation title and, optionally, information about the speaker.
It's typically the opening slide in the presentation (unless there's a preshow).

Using a full bleed background image is the best way to establish a setting, set the tone and give the presentation a unique identity.

One way to use a background image while still retaining brand consistency is to select a background image for each topic.
Another is to use the same image but with a different angle or perspective per topic.
For Neo, the image may be a character or scene from the Matrix, thus using the imagery to suggest the topic.
That way, the audience will still associate the image with the brand, but you're able to get away from a stark, corporate-looking title slide.

== Speaker / Credentials

A _speaker / credentials slide_ communicates information about the speaker to the audience.
This slide should only contain essential information:

* Speaker name
* Speaker title
* Speaker headshot
* Up to two contact addresses (e-mail, link, screenname)

It's important to personalize this slide with a picture of yourself, but otherwise keep it lean.
The audience wants to get to know you, but they don't need your life story.
Remember that they are there to learn about the topic, not your life.
What's important is that they understand that if they need to contact you, the information is there for them to find it later.

Introduce yourself and move on.

A good example of this slide type can be found in the https://speakerdeck.com/pedronauck/reactjs-keep-simple-everything-can-be-a-component[Keep it Simple, Everything Can Be a Component] deck.

== Agenda

An _agenda slide_ contains a list of each major topic in the presentation, serving as the presentation's table of contents.
This slide can be used to set the audience's expectations.
What can they expect to learn?
What's not covered?
Set up their internal progress bar so they can be prepared to take in all the information that's coming to them.

Eventually, we envision this slide being generated automatically from the topic slides and, perhaps, inserted between each topic automatically to serve as a checkpoint in the presentation.

We strongly recommend against using a progress bar on each slide.
That draws too much attention to the progress and away from the story.
You want some mystery.
The agenda slide can be used to give them a break, reward them by reminding them of what they've learned and ensure they only think about progress when you want them to.

One interesting idea is to associate each agenda item with an icon and then use the list of icons as a way to show progress.
For an example, see https://speakerdeck.com/orderedlist/producing-creativity[Producing Creativity].

=== Schedule

A _schedule slide_ is similar to an agenda, but it incorporates time and external events, such as a coffee break or lunch.
The content should be very high level so that the focus is on the when and not the what.

It might help to use a daily agenda-style layout (e.g., grid) to reinforce its purpose and make it easy to remember.
For instance, think of the agenda-style layout used for a conference schedule.

== Topic

A _topic slide_ consists of a title (or statement) and, ideally, supporting imagery for that topic.
These slides identify the presentation "`chapters`" and likely map back to an entry on the _agenda slide_.
Each topic slide will use one of several predefined layouts and either the same image throughout the presentation or an image per topic.

A topic slide helps transition from one topic to another.
It also gives the audience a short break, let's them come up for air and prepare their brains to start learning something new.

A good way to break up the monotony and rigity of plain topics is to replace it with a question instead.
You are likely introducing a topic to answer a question or address a need.
So start off by posing the question or challenge and then use the material to address it.

Don't give in to the temptation of adding content to the topic slide.
In other words, don't give anything away yet.
Let the topic sit out there and take hold in the audiences' brains.
Antici...

== Subject

Sometimes, you want to put a subject into the audience's mind so you can speak about it.
A _subject slide_ communicates the current subject (proper noun) of discussion.
It may be a photo of a person or place or another visual identifier (e.g., a logo).
If necessary, a caption can be added to explicitly label the subject, but it's most effective if the image can stand alone.

It's tempting to want to crowd the slide with (random) facts about the subject in the form of bullets.
Don't do it!
You want the audience to focus on what you are saying, your message, not trying to figure out what all the facts mean and how they relate to what you're jabbering on about.

== Exercise

An _exercise slide_ defines a task or challenge for the audience to complete.
The slide should not state all the details.
It should only serve as a tickler to remind the audience of the goal at hand and provide a countdown (in minute increments at the shortest) to show when the task is expected to be complete.

Use a background image to communicate how the exercise should be conducted.
For instance, if it's a group exercise, show people working together.
If it's an individual challenge, show someone working alone.

Shoot for making the slide look like a poster.
It should merely be a backdrop for the activity that's going on in the room.
If there are details that need to be shared, they should be done verbally or included in a handout.

== Image

An _image slide_ contains of an image and, optionally, a caption.

Unless you have reason not to, use the entire canvas to display the image.
Images establish setting and that doesn't work if the image is boxed in.
Focus the part of the image you really want them to look at (zoom, spotlight, focus blur).
Give the image motion using a subtle transition.
Remember that the eye stops noticing something unless it is moving, and you want the audience to stay focused on what you are showing them.

The image is specified using a block image macro.
The caption is specified either as the section title or the block title, which may affect how it gets displayed.
By default, the image is displayed centered on the page in it's native resolution.
One or more roles can be used to control how it fits in the page.
The most common is `.background.fit`, which will fit the image to the background size.

One way to display a caption is using a band across the page.
Another is to put a layer mask on one half of the image (vertical or horizontal) and put the text on the masked area.

If you are going to add a caption, consider showing the image first then adding the caption after they've soaked it up.
This not only helps layer / unfold the story, it gives them one thing to comprehend at a time.

== Quote

A _quote slide_ contains a spoken or written quote by a person or other source.
The quotation is the focus of the slide and should be the only thing on the slide, or at least, stand out as much as possible.

Quote slides are a very effective way to introduce topics or make statements.
You are, in effect, bringing the other person on stage to make their statement.
This introduces the opportunity to state your support or rebuttal in a way that seems very natural to the audience.
A video of the quote is even better (if the medium supports it).

If the quote is long, excerpts in the quote should be emphasized or highlighted.
To reach the audience emotionally, an image of the author (or source) should be added, either in a callout circle or as a full-bleed backdrop.
If using a backdrop, a subtle and steady transition on the backdrop helps bring the quote to life.

As an alternative to the image of the speaker or source, a background image or video can be added that reinforces the quote's message or otherwise establishes the setting, mood or tone.

=== Dialogue / Conversation

A _dialogue / conversation slide_ is similar to a quote slide except there is more than one “voice” being represented.
While a quote helps support a point, a dialogue helps show that there are multiple sides to the story and gets the audience thinking about where they side.
It might also help to get a discussion started in the room.
Seeing that people have different views makes audience members aware they might have their own to share.

== Code

A _code slide_ contains sample source code along with zero or more callouts.
Code is very meaningful to the Neo audience and thus should be given the maximum attention on the slide.
That means the code should be centered, take up as much space on the slide as possible and be displayed in a large, readable font.
Syntax highlighting should be used when it helps increase the contrast of the keywords or makes the overall structure more readable.
However, don't just color for color's sake.

High contrast (dark background, light text) can be used to "dim the lights" and put the code in the spotlight.
Consider breaking from the traditional top-down flow and put callouts above and below and code to keep the code centered.

A code slide may be cause and effect (e.g., a query and its results) or an anatomy (e.g., a code listing that you examine and/or explain).

Avoid the temptation of cramming numerous examples on a single slide.
Progress the audience gradually by giving each distinct code snippet its own slide.

== Statement / Question / Advice

A _statement / question / advice slide_ reinforces the central point, takeaway or crux of a longer explanation or makes a transition (rising action) from one point to another.
It might be something the audience records word-for-word in their notebook or tweets.
It also reminds the audience where they are in the narrative, grounds them or invites them alone with you on the journey.

Since a statement slide is all about the words, you should leverage typography to its full extent to turn the words into imagery.
The words should be big and bold or otherwise stand out.
A display font works best here.
Use color to make it less stark and to emphasize key words.

== List

Humans love to create lists, but audiences don't always like to receive them.
If you must, at least try to dress it up as something other than a list and _don't use bullets_!
And avoid using subitems at all cost.

A _list slide_ shows a collection of unordered items.
It may also have a title or label to introduce the list and a summary that wraps up the point or reinforces the relationship between the items.
While it's tempting to put the label above and summary below, consider a horizontal arrangement instead.

Various techniques can be used to encourage focus on the current item (i.e., one item at a time).
These techniques include:

* incremental reveal
* shy (dim previous item)
* change color
* grow / shrink
* overlay / swap
* scatter

== Sequence / Ranking

A _sequence slide_ is similar to a list slide except it assigns an explicit ordering to the items.
Having said that, ensure that the items really are part of a sequence and that you're not just imposing an order on them.

The same techniques can be used to encourage focus on the current item.
However, a better technique to consider is to split the list into multiple slides so each item gets its own canvas.
That breaks you out of the habit of creating subitems.
Instead, you can use intermediatary slides to reinforce a point before moving on to the next item.
A good example of this technique is https://speakerdeck.com/hatefulcrawdad/stop-working-from-a-prison-cell[Stop Working from a Prison Cell].

== Axis
//== Contrast / Juxtapose / Division / Partition / Axis

An _axis slide_ presents two or more subjects to emphasize the distinction between them.
It might be something like a Yin and Yang or two sides of a coin.
This type of slide usually shows the subjects with a dividing line between them.
A good example of this slide type can be found in the https://speakerdeck.com/pedronauck/reactjs-keep-simple-everything-can-be-a-component[Keep it Simple, Everything Can Be a Component] deck.
